# Generated by Django 2.2.7 on 2019-11-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eTangun', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leveldict',
            name='belt_type',
            field=models.CharField(max_length=4),
        ),
    ]
