# Generated by Django 2.2.7 on 2019-11-12 13:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eTangun', '0002_auto_20191109_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leveldict',
            name='belt_type',
        ),
        migrations.RemoveField(
            model_name='leveldict',
            name='level',
        ),
        migrations.AddField(
            model_name='leveldict',
            name='belt_level',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(blank=True, default=datetime.datetime.now)),
                ('group', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('belt_level', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='eTangun.LevelDict')),
            ],
        ),
    ]
