# Generated by Django 2.2.7 on 2019-11-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eTangun', '0003_auto_20191112_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
