# Generated by Django 2.2.7 on 2019-11-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eTangun', '0004_members_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='gender',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='members',
            name='login',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
