# Generated by Django 2.2.7 on 2019-11-24 17:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eTangun', '0005_auto_20191123_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('post_code', models.CharField(max_length=10)),
                ('street_address', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField()),
                ('competition_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eTangun.Addresses')),
                ('competition_active', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eTangun.CompetitionDict')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eTangun.Members')),
            ],
        ),
    ]
