# Generated by Django 2.2.7 on 2019-11-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eTangun', '0007_auto_20191125_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='country',
            field=models.CharField(default='pl', max_length=2),
        ),
    ]
