# Generated by Django 2.2.7 on 2019-12-03 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eTangun', '0008_addresses_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('payment', models.IntegerField()),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eTangun.Members')),
            ],
        ),
    ]
